# Custom CNN Configuration - Base variant
# This configuration defines a custom CNN architecture using the flexible framework

# Model configuration
model:
  architecture: flexible_cnn
  input_channels: 3
  num_classes: 30
  
  # Custom CNN specific configuration (used by FlexibleCNN)
  conv_layers: [32, 64, 128, 256, 512]  # Number of filters in each block
  fc_layers: [512, 256]  # Fully connected layer sizes
  kernel_size: 3
  pool_size: 2
  dropout: 0.5
  activation: relu
  pooling_type: max
  use_batch_norm: true

# Training configuration
training:
  num_epochs: 30
  batch_size: 32
  loss_function: cross_entropy
  
  # Optimization
  optimizer:
    name: adamw
    learning_rate: 0.001
    weight_decay: 0.0005
    
    # SGD specific
    momentum: 0.9
    nesterov: true
    
    # Adam/AdamW specific
    beta1: 0.9
    beta2: 0.999
    
  # Learning rate scheduling  
  scheduler:
    name: onecycle
    max_lr: 0.01
    
    # StepLR parameters
    step_size: 7
    gamma: 0.1
    
    # ReduceLROnPlateau parameters
    patience: 3
    factor: 0.1
    
    # CosineAnnealingLR parameters
    t_max: 30
    
    # Warmup
    use_warmup: true
    warmup_epochs: 3

# Data configuration
data:
  img_size: 224
  data_dir: data\raw\30_Musical_Instruments\
  num_workers: 4
  pin_memory: true
  train_val_split: 0.8
  use_weighted_sampler: false

# Augmentation
augmentation:
  use_augmentation: true
  augmentation_strength: medium
  
  # Advanced transforms if needed
  use_mixup: false
  mixup_alpha: 0.2
  use_cutmix: false
  cutmix_alpha: 1.0

# Experiment tracking
experiment:
  save_model: true
  save_dir: experiments/custom_cnn_base
  checkpoint_frequency: 5
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
